name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Clone GitHub repo
        uses: actions/checkout@v3

      - name: Push to GitLab
        run: |
          git config --global user.name "TechmoNoway"
          git config --global user.email "cuty0406@outlook.com"
          git remote add gitlab https://TechmoNoway:${{ secrets.GITLAB_TOKEN }}@gitlab.com/TechmoNoway/<repo>.git
          git push gitlab main
